version: "3"
services:
  db:
    container_name: pg-local
    image: postgres:11-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: cc01
    volumes:
      - postgres_data:/var/lib/postgresql/data
  admin:
    container_name: adminer-local
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 9090:8080
  web:
    container_name: cc01-local
    environment:
      - DATABASE_URL=postgres://admin:admin@pg-local/postgres
      - RUST_BACKTRACE=1
    image: cc01:stage
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
    ports:
      - 8098:8088
volumes:
  postgres_data:
networks: 
  cc01-nw:
